// Generated by CoffeeScript 1.3.3

enchant();

window.onload = function() {
  var game;
  game = new Game(320, 320);
  game.fps = 15;
  game.preload("images/chara1.png");
  game.onload = function() {
    var bear;
    bear = new Sprite(32, 32);
    bear.image = game.assets["images/chara1.png"];
    bear.x = 0;
    bear.y = 0;
    bear.frame = 5;
    game.rootScene.addChild(bear);
    bear.addEventListener("enterframe", function() {
      this.x += 1;
      return this.frame = this.age % 2 + 6;
    });
    return bear.addEventListener("touchstart", function() {
      return game.rootScene.removeChild(bear);
    });
  };
  return game.start();
};
